//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DWS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close1 {
            get {
                object obj = ResourceManager.GetObject("close1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close2 {
            get {
                object obj = ResourceManager.GetObject("close2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error check update.
        ///Message: {0}.
        /// </summary>
        internal static string MainDwsForm_AutoUpdate_ {
            get {
                return ResourceManager.GetString("MainDwsForm_AutoUpdate_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version avalible.
        ///
        ///Version: {0} ..
        /// </summary>
        internal static string MainDwsForm_AutoUpdate1_ {
            get {
                return ResourceManager.GetString("MainDwsForm_AutoUpdate1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Builder 3D.
        /// </summary>
        internal static string MainDwsForm_ChangeLanguage__0__Builder_3D {
            get {
                return ResourceManager.GetString("MainDwsForm_ChangeLanguage__0__Builder_3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Camera.
        /// </summary>
        internal static string MainDwsForm_ChangeLanguage__0__Camera {
            get {
                return ResourceManager.GetString("MainDwsForm_ChangeLanguage__0__Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Groove Music, Film TV.
        /// </summary>
        internal static string MainDwsForm_ChangeLanguage__0__Groove_Music__Film_TV {
            get {
                return ResourceManager.GetString("MainDwsForm_ChangeLanguage__0__Groove_Music__Film_TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Mail, Calendar, Maps.
        /// </summary>
        internal static string MainDwsForm_ChangeLanguage__0__Mail__Calendar__Maps {
            get {
                return ResourceManager.GetString("MainDwsForm_ChangeLanguage__0__Mail__Calendar__Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Money, Sports, News, Weather.
        /// </summary>
        internal static string MainDwsForm_ChangeLanguage__0__Money__Sports__News__Weather {
            get {
                return ResourceManager.GetString("MainDwsForm_ChangeLanguage__0__Money__Sports__News__Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Office 2016 Telemetry.
        /// </summary>
        internal static string MainDwsForm_ChangeLanguage__0__Office_2016_Telemetry {
            get {
                return ResourceManager.GetString("MainDwsForm_ChangeLanguage__0__Office_2016_Telemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} People, OneNote.
        /// </summary>
        internal static string MainDwsForm_ChangeLanguage__0__People__OneNote {
            get {
                return ResourceManager.GetString("MainDwsForm_ChangeLanguage__0__People__OneNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Phone Companion.
        /// </summary>
        internal static string MainDwsForm_ChangeLanguage__0__Phone_Companion {
            get {
                return ResourceManager.GetString("MainDwsForm_ChangeLanguage__0__Phone_Companion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Photos.
        /// </summary>
        internal static string MainDwsForm_ChangeLanguage__0__Photos {
            get {
                return ResourceManager.GetString("MainDwsForm_ChangeLanguage__0__Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Solitaire Collection.
        /// </summary>
        internal static string MainDwsForm_ChangeLanguage__0__Solitaire_Collection {
            get {
                return ResourceManager.GetString("MainDwsForm_ChangeLanguage__0__Solitaire_Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} UAC.
        /// </summary>
        internal static string MainDwsForm_ChangeLanguage__0__UAC {
            get {
                return ResourceManager.GetString("MainDwsForm_ChangeLanguage__0__UAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Voice Recorder.
        /// </summary>
        internal static string MainDwsForm_ChangeLanguage__0__Voice_Recorder {
            get {
                return ResourceManager.GetString("MainDwsForm_ChangeLanguage__0__Voice_Recorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Windows Update.
        /// </summary>
        internal static string MainDwsForm_ChangeLanguage__0__Windows_Update {
            get {
                return ResourceManager.GetString("MainDwsForm_ChangeLanguage__0__Windows_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} XBOX.
        /// </summary>
        internal static string MainDwsForm_ChangeLanguage__0__XBOX {
            get {
                return ResourceManager.GetString("MainDwsForm_ChangeLanguage__0__XBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v{0}.
        /// </summary>
        internal static string MainDwsForm_MainDwsForm_v_0_ {
            get {
                return ResourceManager.GetString("MainDwsForm_MainDwsForm_v_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroy Windows 10 Spying - {0}!.
        /// </summary>
        internal static string MainDwsForm_SetCompleteText_Destroy_Windows_10_Spying____0__ {
            get {
                return ResourceManager.GetString("MainDwsForm_SetCompleteText_Destroy_Windows_10_Spying____0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroy Windows 10 Spying - errors: {0}.
        /// </summary>
        internal static string MainDwsForm_SetCompleteText_Destroy_Windows_10_Spying___errors___0_ {
            get {
                return ResourceManager.GetString("MainDwsForm_SetCompleteText_Destroy_Windows_10_Spying___errors___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minimize {
            get {
                object obj = ResourceManager.GetObject("minimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minimize1 {
            get {
                object obj = ResourceManager.GetObject("minimize1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minimize2 {
            get {
                object obj = ResourceManager.GetObject("minimize2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
